name: Sync with Upstream Repository

on:
  # Runs on a schedule (every 6 hours)
  schedule:
    - cron: '0 */6 * * *'
  
  # Manual trigger
  workflow_dispatch:

jobs:
  sync:
    name: Sync with upstream repository
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        base_branch: 
          - rolling
          - iron
          - humble
          - foxy

    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      
      - name: Run sync-branches
        uses: autowarefoundation/autoware-github-actions/sync-branches@v1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          base-branch: ${{ matrix.base_branch }}
          sync-pr-branch: sync-upstream-${{ matrix.base_branch }}
          sync-target-repository: https://github.com/ros2/launch.git
          sync-target-branch: ${{ matrix.base_branch }}
          pr-title: "chore: sync upstream ${{ matrix.base_branch }}"
          pr-labels: |
            bot
            sync-upstream
          auto-merge-method: merge
